-- SQL script to create Users table for MyAspNetApp
CREATE TABLE dbo.Users (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Username NVARCHAR(100) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(256) NOT NULL,
    Salt NVARCHAR(128) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

-- Example insert (password 'P@ssw0rd' with generated salt and SHA256 hash should be generated by your app)
-- INSERT INTO dbo.Users (Username, PasswordHash, Salt) VALUES ('alice', '<hex-hash>', '<salt>');
